config/routes.rb
Rails.application.routes.draw do

	devise_for :users, path_names: {
		sign_up: '' #Stop Sign Up
	}

	root to: "orders#index"
  
 	resources :orders
  resources :products

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :orders, :through=> :product_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_action :authenticate_user!

  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
    @order = Order.new
    @product = Product.all
  end

  def create
    @order = Order.new(params.require(:order).permit(:name, :phone, :address, :delivery_date, :product_id, :payment_option, :quantity, :order_status))

    if @order.save
      redirect_to orders_path, :notice=> 'Order was successfully created.'
    else
      redirect_to new_order_path, :alert=> 'Error! Please try again'
    end
  end

  def edit
    @order = Order.find(params[:id])
    @product = Product.all
  end

  def update
    @order = Order.find(params[:id])

    if @order.update(params.require(:order).permit(:name, :phone, :address, :delivery_date, :product_id, :payment_option, :quantity, :order_status))
      redirect_to orders_path, :notice=> 'Order was successfully updated.'
    else
      redirect_to new_order_path, :alert=> 'Error! Please try again'
    end
  end

  def destroy
    @order = Order.find(params[:id])
    if @order.destroy
      redirect_to orders_path, :notice => 'Order was successfully deleted.'
    else
      redirect_to orders_path, :alert => 'Error! Please try again'
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  before_action :authenticate_user!

  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
  end  

  def create
    @product = Product.new(params.require(:product).permit(:product_name, :product_details, :price))

    if @product.save
      redirect_to products_path, :notice=> 'Product was successfully created.'
    else
      redirect_to new_product_path, :alert=> 'Error! Please try again'
    end
  end

  def edit
  end

  def update
  end

  def destroy
    @order = Order.where("product_id = ?", params[:id])

    if @order.count > 0
      redirect_to products_path, :alert => 'Cannot delete product while its order exists.'
    else  
      @product = Product.find(params[:id])

      if @product.destroy
        redirect_to products_path, :notice => 'Product was successfully deleted.'
      else
        redirect_to products_path, :alert => 'Error! Please try again'
      end
    end  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<% if user_signed_in? %>

<!DOCTYPE html>
  <html>

    <head>

      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">

      <title><%= yield(:title) %> | RailsOMS</title>
      <%= csrf_meta_tags %>

      <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
      <%= stylesheet_link_tag    'application', :media => "all" %>
      <%= stylesheet_link_tag    'print', :media => "print" %>

    </head>

    <body class="fixed-nav fixed-nav-basic"> <!-- min sidemenu: mini-navbar-->
    <div id="wrapper">
      <nav class="navbar-default navbar-static-side" role="navigation">
        <div class="sidebar-collapse">
          <ul class="nav metismenu" id="side-menu">
            <li class="nav-header">
              <div class="dropdown profile-element">
                <span>
                  <h2 style="font-size: 30px; margin-bottom: 20px; color: #f70b0b">INFORTECH <span style="color: #1ab394; font-weight: 900">Solutions</span></h2>
                </span>
                <!--<a data-toggle="dropdown" class="dropdown-toggle" href="#">
                  <span class="clear">
                      <span class="block m-t-xs">
                          <strong class="font-bold">RailsOMS Application</strong> <b class="caret"></b>
                      </span>
                  </span>
                </a>
                <ul class="dropdown-menu animated fadeInRight m-t-xs">
                  <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
                </ul>-->
              </div>
              <div class="logo-element">
                <h2 style="font-size: 10px; margin-top: 0px; margin-bottom: 0px; color: #f70b0b">INFORTECH <span style="color: #1ab394; font-weight: 900">Solutions</span></h2>
              </div>
            </li>
            <li class="landing_link">
              <%= link_to orders_path do %>
                <i class="fa fa-th-large"></i> <span class="nav-label">Dashboard</span> <span class="label label-warning pull-right">HOME</span></a>
              <% end %>
            </li>
            <li class="">
              <a href="index.html"><i class="fa fa-shopping-bag"></i> <span class="nav-label">Order</span> <span class="fa arrow"></span></a>
              <ul class="nav nav-second-level">
                <li><%= link_to "All Orders", orders_path %></li>
                <li class=""><%= link_to "Add Order", new_order_path %></li>
              </ul>
            </li>
            <li class="">
              <a href="index.html"><i class="fa fa-product-hunt"></i> <span class="nav-label">Product</span> <span class="fa arrow"></span></a>
              <ul class="nav nav-second-level">
                <li><%= link_to "All Products", products_path %></li>
                <li class=""><%= link_to "Add Product", new_product_path %></li>
              </ul>
            </li>
            <li>
              <a href="#"><i class="fa fa-cog fa-spin"></i> <span class="nav-label">Profile</span><span class="fa arrow"></span></a>
              <ul class="nav nav-second-level collapse">
                <li><%= link_to "Change Password", edit_user_registration_path %></li>
                <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
              </ul>
            </li>
          </ul>
        </div>
      </nav>

      <div id="page-wrapper" class="gray-bg" style="min-height: 600px;">
        <div class="row border-bottom">
          <nav class="navbar navbar-fixed-top white-bg" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
              <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
            </div>
            <ul class="nav navbar-top-links navbar-right">
              <li style="padding: 20px 10px">
                <span class="m-r-sm text-muted"><strong>RailsOMS</strong> Application.</span>
              </li>
              <li class="pull-right">
                <%= link_to destroy_user_session_path, :method => 'delete' do %>
                    <i class="fa fa-sign-out"></i> Log out
                <% end %>
              </li>
            </ul>
          </nav>
        </div>

        <div class="wrapper wrapper-content">

          <% if notice %>
              <div class="alert alert-info">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <strong>Notice!</strong> <%= notice %>
              </div>
          <% end %>

          <% if alert %>
              <div class="alert alert-danger">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <strong>Alert!</strong> <%= alert %>
              </div>
          <% end %>

          <%= yield %>

        </div>

        <div class="footer">
          <div class="pull-right">
            BY <strong><span style="color: green">INZAMUL</span><span style="color:red"> HAQUE</span></strong>
          </div>
          <div>
            <strong>Copyright</strong> INFORTECH Solutions &copy; <%= Time.now.year %>
          </div>
        </div>
      </div>
    </div>

    <!-- Mainly scripts -->
    <%= javascript_include_tag 'application' %>

    <!-- Custom and plugin javascript -->
    <script type="text/javascript">
      $('.i-checks').iCheck({
        checkboxClass: 'icheckbox_square-green',
        radioClass: 'iradio_square-green'
      });
    </script>

    <% if notice %>
      <script>
        $(document).ready(function() {
          setTimeout(function() {
            toastr.options = {
              closeButton: true,
              progressBar: true,
              showMethod: 'slideDown',
              timeOut: 4000
            };
            toastr.success('<%= notice %>', 'Notice');
          }, 1300);
        });
      </script>
    <% end %>

    <script>
      $(document).ready(function(){
        $('.dataTables-example').DataTable({
          order: [[ 0, "desc" ]],
          dom: '<"html5buttons"B>lTfgitp',
          buttons: [
            { extend: 'copy'},
            {extend: 'csv'},
            {extend: 'excel', title: 'ExampleFile'},
            {extend: 'pdf', title: 'ExampleFile'},

            {extend: 'print',
              customize: function (win){
                $(win.document.body).addClass('white-bg');
                $(win.document.body).css('font-size', '10px');

                $(win.document.body).find('table')
                    .addClass('compact')
                    .css('font-size', 'inherit');
              }
            }
          ]

        });
      });
    </script>

    <script type="text/javascript">
      $('#product_id').select2();
    </script>

    </body>
  </html>


<% else %>

<!DOCTYPE html>
  <html>

    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">

      <title>Login | RailsOMS</title>
      <%= csrf_meta_tags %>

      <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
      <%= stylesheet_link_tag    'application' %>
    </head>

    <body class="gray-bg">
    <div class="middle-box text-center loginscreen animated fadeInDown">
      <div>

        <%= yield %>

      </div>
    </div>

    <div class="footer">
      <div class="pull-right">
        BY <strong><span style="color: green">INZAMUL</span><span style="color:red"> HAQUE</span></strong>
      </div>
      <div>
        <strong>Copyright</strong> INFORTECH Solutions &copy; <%= Time.now.year %>
      </div>
    </div>

    <!-- Mainly scripts -->
    <%= javascript_include_tag 'application' %>

    </body>

  </html>

<% end %>

app/views/orders/edit.html.erb
<% content_for :title, "Edit Order" %>

<div class="ibox float-e-margins">
  <div class="ibox-title">
    <h5>Add Order <small>Please </small></h5>
    <div class="ibox-tools">
      <a class="collapse-link">
        <i class="fa fa-chevron-up"></i>
      </a>
      <a class="close-link">
        <i class="fa fa-times"></i>
      </a>
    </div>
  </div>
  <div class="ibox-content">
    <div class="row">
      <%= form_for @order do|f| %>
          <div class="col-sm-6 b-r">
            <h3 class="m-t-none m-b">Customer Info</h3>
            <div class="form-group">
              <label>Name</label>
              <%= f.text_field :name, :placeholder=>"Enter full name", :class=>"form-control", :required=>'' %>
            </div>
            <div class="form-group">
              <label>Phone</label>
              <%= f.text_field :phone, :placeholder=>"Enter phone number", :class=>"form-control", :required=>'' %>
            </div>
            <div class="form-group">
              <label>Address</label>
              <%= f.text_area :address, :placeholder=>"Enter full address", :class=>"form-control", :rows=>"3", :required=>'' %>
            </div>
          </div>
          <div class="col-sm-6"><h3 class="m-t-none m-b">Order Info</h3>
            <div class="form-group">
              <label>Delivery Date</label>
              <%= f.date_field :delivery_date, :class=>'form-control', :required=>'' %>
            </div>
            <div class="form-group">
              <label>Product</label>
              <% options = options_from_collection_for_select(@product, 'id', 'product_name', :selected => f.object.product_id) %>
              <%= f.select :product_id,  options, {:include_blank => false}, {:class=>'form-control m-b select2_demo_1', :id=>'product_id'} %>
            </div>
            <div class="row">
              <div class="col-sm-6">
                <div class="form-group">
                  <label>Select Payment Option</label>
                  <%= f.select :payment_option, options_for_select(['Postpay', 'Prepay (Full)', 'Prepay (Half)'], :selected => f.object.payment_option), {:include_blank => false}, {:class=>'form-control m-b'} %>
                </div>
              </div>
              <div class="col-sm-6">
                <div class="form-group">
                  <label>Quantity</label>
                  <%= f.text_field :quantity, :placeholder=>"Enter total amount", :type=>'number', :class=>"form-control", :required=>'' %>
                </div>
              </div>
            </div>
          </div>
          <div class="col-sm-12">
            <div class="row">
              <div class="hr-line-dashed"></div>
              <div class="form-group">
                <label class="col-sm-2">Status</label>
                <div class="col-sm-10">
                  <div class="row">                   
                    <div class="col-md-2"><label class="checkbox-inline i-checks"> <%= f.radio_button :order_status, 'Confirm', :class=>'icheckbox_square-green' %> Confirm </label></div>
                    <div class="col-md-2"><label class="checkbox-inline i-checks"> <%= f.radio_button :order_status, 'Ready', :class=>'icheckbox_square-green' %> Ready </label></div>
                    <div class="col-md-2"><label class="checkbox-inline i-checks"> <%= f.radio_button :order_status, 'Send', :class=>'icheckbox_square-green' %> Send </label></div>
                    <div class="col-md-2"><label class="checkbox-inline i-checks"> <%= f.radio_button :order_status, 'Delivered', :class=>'icheckbox_square-green' %> Delivered </label></div>
                    <div class="col-md-2"><label class="checkbox-inline i-checks"> <%= f.radio_button :order_status, 'Returned', :class=>'icheckbox_square-green' %> Returned </label></div>
                    <div class="col-md-2"><label class="checkbox-inline i-checks"> <%= f.radio_button :order_status, 'Cancelled', :class=>'icheckbox_square-green' %> Cancelled </label></div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-sm-12">
            <div class="hr-line-dashed"></div>
            <%= f.submit :class=>"btn btn-sm btn-primary pull-right m-t-n-xs" %>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/orders/index.html.erb
<% content_for :title, "All Orders" %>

<div class="row">
  <div class="col-lg-12">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h5>All Orders Data</h5>
        <div class="ibox-tools">
          <a class="collapse-link">
            <i class="fa fa-chevron-up"></i>
          </a>
          <a class="close-link">
            <i class="fa fa-times"></i>
          </a>
        </div>
      </div>
      <div class="ibox-content">

        <div class="table-responsive">
          <table class="table table-striped table-bordered table-hover dataTables-example">
            <thead>
              <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Phone</th>
                <th>Address</th>
                <th>Delivery Date</th>
                <th>Product</th>
                <th>Price</th>
                <th>Qty</th>
                <th>Total</th>
                <th>Payment Option</th>
                <th>Status</th>
                <th width="101px">Buttons</th>
              </tr>
            </thead>

            <tbody>

            <% @orders.each  do |order| %>

              <tr class="">
                <td><%= order.id %></td>
                <td><%= order.name %></td>
                <td><%= order.phone %></td>
                <td><%= order.address %></td>
                <td><%= order.delivery_date %></td>
                <td><%= order.product.product_name %></td>
                <td><%= order.product.price %></td>
                <td><%= order.quantity %></td>
                <td><%= order.product.price * order.quantity %></td>
                <td><%= order.payment_option %></td>

                  <% if order.order_status == 'Confirm'  %>
                    <td><span class="badge badge-white"> <%= order.order_status %></span></td>
                  <% elsif order.order_status == 'Ready' %>
                    <td><span class="badge badge-warning"> <%= order.order_status %></span></td>
                  <% elsif order.order_status == 'Send' %>
                    <td><span class="badge badge-success"> <%= order.order_status %></span></td>
                  <% elsif order.order_status == 'Delivered' %>
                    <td><span class="badge badge-primary"> <%= order.order_status %></span></td>
                  <% elsif order.order_status == 'Returned' %>
                    <td><span class="badge badge-danger"> <%= order.order_status %></span></td>
                  <% elsif order.order_status == 'Cancelled' %>
                    <td><span class="badge badge-inverse"> <%= order.order_status %></span></td>
                  <% end %>
                <td>
                  <%= link_to order_path(order.id), :class=>'btn btn-white btn-bitbucket', method: :delete, data: {confirm: 'Are you sure?'} do %>
                    <i class="fa fa-trash-o" aria-hidden="true"></i>
                  <% end %>
                  <%= link_to edit_order_path(order.id), :class=>'btn btn-white btn-bitbucket' do %>
                      <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                  <% end %>
                  <%= link_to order_path(order.id), :class=>'btn btn-white btn-bitbucket' do %>
                      <i class="fa fa-print" aria-hidden="true"></i>
                  <% end %>
                </td>
              </tr>

            <% end %>

            </tbody>
          </table>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/orders/new.html.erb
<% content_for :title, "Add Order" %>

<div class="ibox float-e-margins">
  <div class="ibox-title">
    <h5>Add Order <small>Please </small></h5>
    <div class="ibox-tools">
      <a class="collapse-link">
        <i class="fa fa-chevron-up"></i>
      </a>
      <a class="close-link">
        <i class="fa fa-times"></i>
      </a>
    </div>
  </div>
  <div class="ibox-content">
    <div class="row">
      <%= form_for @order do|f| %>
          <div class="col-sm-6 b-r"><h3 class="m-t-none m-b">Customer Info</h3>
            <div class="form-group">
              <label>Name</label>
              <%= f.text_field :name, :placeholder=>"Enter full name", :class=>"form-control", :required=>'' %>
            </div>
            <div class="form-group">
              <label>Phone</label>
              <%= f.text_field :phone, :placeholder=>"Enter phone number", :class=>"form-control", :required=>'' %>
            </div>
            <div class="form-group">
              <label>Address</label>
              <%= f.text_area :address, :placeholder=>"Enter full address", :class=>"form-control", :rows=>"3", :required=>'' %>
            </div>
          </div>
          <div class="col-sm-6"><h3 class="m-t-none m-b">Order Info</h3>
            <div class="form-group">
              <label>Delivery Date</label>
              <%= f.date_field :delivery_date, :class=>'form-control', :required=>'' %>
            </div>
            <div class="form-group">
              <label>Product</label>
              <% options = options_from_collection_for_select(@product, 'id', 'product_name') %>
              <%= f.select :product_id,  options, {:include_blank => 'Please Select'}, {:class=>'form-control m-b select2_demo_1', :id=>'product_id', :required=>''} %>
            </div>
            <div class="row">
              <div class="col-sm-6">
                <div class="form-group">
                  <label>Select Payment Option</label>
                  <%= f.select :payment_option, options_for_select([ 'Postpay', 'Prepay (Full)', 'Prepay (Half)'], :selected=>'Postpay'), {:include_blank => false}, {:class=>'form-control m-b'} %>
                </div>
              </div>
              <div class="col-sm-6">
                <div class="form-group">
                  <label>Quantity</label>
                  <%= f.text_field :quantity, :placeholder=>"Enter Quantity", :type=>'number', :class=>"form-control", :required=>'', :value=>'1' %>
                </div>
              </div>
            </div>
          </div>
          <div class="col-sm-12">
            <div class="row">
              <div class="hr-line-dashed"></div>
              <div class="form-group">
                <label class="col-sm-2">Status</label>
                <div class="col-sm-10">
                  <div class="row">
                    <div class="col-md-2"><label class="checkbox-inline i-checks"> <%= f.radio_button :order_status, 'Confirm', :class=>'icheckbox_square-green' %> Confirm </label></div>
                    <div class="col-md-2"><label class="checkbox-inline i-checks"> <%= f.radio_button :order_status, 'Ready', :class=>'icheckbox_square-green' %> Ready </label></div>
                    <div class="col-md-2"><label class="checkbox-inline i-checks"> <%= f.radio_button :order_status, 'Send', :class=>'icheckbox_square-green' %> Send </label></div>
                    <div class="col-md-2"><label class="checkbox-inline i-checks"> <%= f.radio_button :order_status, 'Delivered', :class=>'icheckbox_square-green' %> Delivered </label></div>
                    <div class="col-md-2"><label class="checkbox-inline i-checks"> <%= f.radio_button :order_status, 'Returned', :class=>'icheckbox_square-green' %> Returned </label></div>
                    <div class="col-md-2"><label class="checkbox-inline i-checks"> <%= f.radio_button :order_status, 'Cancelled', :class=>'icheckbox_square-green' %> Cancelled </label></div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-sm-12">
            <div class="hr-line-dashed"></div>
            <%= f.submit :class=>"btn btn-sm btn-primary pull-right m-t-n-xs" %>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/orders/show.html.erb
<% content_for :title, "Print Order" %>

<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-8">
    <h2>Invoice</h2>
    <ol class="breadcrumb">
      <li>
        <%= link_to 'Home', orders_path%>
      </li>
      <li class="active">
        <strong>Invoice</strong>
      </li>
    </ol>
  </div>
  <div class="col-lg-4">
    <div class="title-action">
      <button href="#" onclick="print_invoice()" class="btn btn-primary"><i class="fa fa-print"></i> Print Invoice </button>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-lg-12">

    <div class="wrapper wrapper-content animated fadeInRight" id="print">
      <div class="ibox-content p-xl">

        <div class="invoice_head">
          <div class="row">
            <div class="col-xs-10">
              <h2 style="font-size: 30px; margin-bottom: 20px; color: #f70b0b">INFORTECH <span style="color: #1ab394; font-weight: 900">Solutions</span></h2>
              <p>
                Company address, Road: xx<br>
                Dhaka 12xx
              </p>
            </div>
          </div>
        </div>
        <hr>
        <h4 class="text-center">INVOICE</h4>
        <div class="row">
          <div class="col-xs-6">
            <h5>To:</h5>
            <address>
              <strong><%= @order.name %></strong><br>
              <%= @order.address %><br>
              <b>Phone :</b> <%= @order.phone %>
            </address>
          </div>

          <div class="col-xs-6 text-right">
            <h4>Invoice No.</h4>
            <h4 class="text-navy">INV-000-<%= @order.id %></h4>
            <p>
              <span><strong>Invoice Date:</strong> Marh 18, 2014</span><br />
              <span><strong>Due Date:</strong> <%= @order.delivery_date %></span>
            </p>
          </div>
        </div>

        <div class="table-responsive m-t">
          <table class="table invoice-table">
            <thead>
              <tr>
                <th>Qty</th>
                <th width="60%" style="text-align: left">Item List</th>
                <th>Rate</th>
                <th>Amount</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><%= @order.quantity %></td>
                <td style="text-align: left">
                  <div>
                    <strong><%= @order.product.id %>. <%= @order.product.product_name %></strong><br>
                    <small><%= @order.product.product_details %></small>
                  </div>
                </td>
                <td>Tk <%= @order.product.price %></td>
                <td>Tk <%= @order.product.price * @order.quantity %></td>
              </tr>
            </tbody>
          </table>
        </div><!-- /table-responsive -->

        <hr style="margin-top: 0px;">

        <div class="row">
          <div class="col-xs-8">
            <div class="well m-t">
              <strong>Comments</strong>
              It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less
            </div>
          </div>
          <div class="col-xs-4">
            <table class="table invoice-total">
              <tbody>
                <tr>
                  <td><strong>Sub Total :</strong></td>
                  <td>Tk <%= @order.product.price * @order.quantity %></td>
                </tr>
                <tr>
                  <td><strong>TAX :</strong></td>
                  <td>Tk 0</td>
                </tr>
                <tr>
                  <td><strong>TOTAL :</strong></td>
                  <td style="border: 1px solid #DDDDDD;">Tk <%= @order.product.price * @order.quantity %></td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-6">
            <p>
              Recvied By : __________________
            </p>
          </div>
          <div class="col-xs-6 text-right">
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  function print_invoice() {
    window.print();
  }
</script>

app/views/products/index.html.erb
<% content_for :title, "All Products" %>

<div class="row">
  <div class="col-lg-12">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h5>All Products Data</h5>
        <div class="ibox-tools">
          <a class="collapse-link">
            <i class="fa fa-chevron-up"></i>
          </a>
          <a class="close-link">
            <i class="fa fa-times"></i>
          </a>
        </div>
      </div>
      <div class="ibox-content">

        <div class="table-responsive">
          <table class="table table-striped table-bordered table-hover dataTables-example">
            <thead>
              <tr>
                <th width="40px">ID</th>
                <th>Product Name</th>
                <th width="50%">Product Details</th>
                <th>Price</th>
                <th width="40px">Buttons</th>
              </tr>
            </thead>

            <tbody>

            <% @products.each  do |product| %>

              <tr class="">
                <td><%= product.id %></td>
                <td><%= product.product_name %></td>
                <td><%= product.product_details %></td>
                <td><%= product.price %></td>
                <td>
                  <%= link_to product_path(product.id), :class=>'btn btn-white btn-bitbucket', method: :delete, data: {confirm: 'Are you sure?'} do %>
                    <i class="fa fa-trash-o" aria-hidden="true"></i>
                  <% end %>
                </td>
              </tr>

            <% end %>

            </tbody>
          </table>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<% content_for :title, "Add Product" %>

<div class="ibox float-e-margins">
  <div class="ibox-title">
    <h5>Add Product <small>Please </small></h5>
    <div class="ibox-tools">
      <a class="collapse-link">
        <i class="fa fa-chevron-up"></i>
      </a>
      <a class="close-link">
        <i class="fa fa-times"></i>
      </a>
    </div>
  </div>
  <div class="ibox-content">
    <div class="row">
      <%= form_for @product do|f| %>
          <div class="col-sm-6"><h3 class="m-t-none m-b">Product Info</h3>
            <div class="form-group">
              <label>Product Name</label>
              <%= f.text_field :product_name, :placeholder=>"Enter product name", :class=>"form-control", :required=>'' %>
            </div>
            <div class="form-group">
              <label>Product Price</label>
              <%= f.text_field :price, :placeholder=>"Enter product price", :class=>"form-control", :type=>'number', :required=>'' %>
            </div>
            <div class="form-group">
              <label>Product Details</label>
              <%= f.text_area :product_details, :placeholder=>"Enter product details", :class=>"form-control", :rows=>"3", :required=>'' %>
            </div>
          </div>
          <div class="col-sm-12">
            <div class="hr-line-dashed"></div>
            <%= f.submit :class=>"btn btn-sm btn-primary pull-right m-t-n-xs" %>
          </div>
      <% end %>
    </div>
  </div>
</div>